image: docker:1.12
services:
  - docker:1.12-dind

stages:
  - test
  - release_gitlab
  - release

variables:
  IMAGE_NAME: nib0r/docker-flow-proxy-letsencrypt
  GITLAB_IMAGE_NAME: docker.nibor.me/robin/docker-flow-proxy-letsencrypt

functional_tests_manual:
  stage: test
  variables:
    DOCKER_CERT_PATH: ${_DOCKER_CERT_PATH}
    DOCKER_HOST: ${_DOCKER_HOST}
    DOCKER_MACHINE_NAME: ${_DOCKER_MACHINE_NAME}
    DOCKER_TLS_VERIFY: ${_DOCKER_TLS_VERIFY}
  script:
    - pip install -r requirements-test.txt --upgrade
    - pytest tests.py
  tags:
    - shell
    - ks2.nibor.me
  when: manual
  only:
    - /^feature-.*$/

functional_tests:
  stage: test
  variables:
    DOCKER_CERT_PATH: ${_DOCKER_CERT_PATH}
    DOCKER_HOST: ${_DOCKER_HOST}
    DOCKER_MACHINE_NAME: ${_DOCKER_MACHINE_NAME}
    DOCKER_TLS_VERIFY: ${_DOCKER_TLS_VERIFY}
  script:
    - pip install -r requirements-test.txt --upgrade
    - pytest tests.py
  tags:
    - shell
    - ks2.nibor.me
  only:
    - develop
    - master
    - tags

test:
  stage: test
  script:
    - pip install -r requirements-test.txt --upgrade
    - pytest app/client_dfple_tests.py
  tags:
    - shell
    - ks2.nibor.me
  only:
    - develop
    - /^feature-.*$/
    - /^release-.*$/
    - master
    - tags

release:
  stage: release
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push $IMAGE_NAME:latest
  tags:
    - docker
    - ks2.nibor.me
  only:
    - master

release_gitlab:
  stage: release_gitlab
  script:
    - docker build -t $GITLAB_IMAGE_NAME:${CI_BUILD_REF_NAME} .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.nibor.me
    - docker push $GITLAB_IMAGE_NAME:${CI_BUILD_REF_NAME}
  tags:
    - docker
    - ks2.nibor.me

release_develop:
  stage: release
  script:
    - docker build -t $IMAGE_NAME:${CI_BUILD_REF_NAME} .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push $IMAGE_NAME:${CI_BUILD_REF_NAME}
  tags:
    - docker
    - ks2.nibor.me
  only:
    - develop

release_tags:
  stage: release
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build -t ${IMAGE_NAME}:${CI_BUILD_TAG} .
    - docker push ${IMAGE_NAME}:$CI_BUILD_TAG
  only:
    - tags
  tags:
    - ks2.nibor.me

