image: docker:git
services:
  - docker:dind

stages:
  - test
  - release

test:
  stage: test

  before_script:
    - mkvirtualenv dfple-test-${CI_BUILD_REF_SLUG}
    - workon dfple-test-${CI_BUILD_REF_SLUG}
  script:
    - pip install -r requirements-test.txt
    - pytest tests.py
  tags:
    - ks2.nibor.me
  only:
    - develop
    - /^feature-.*$/
    - master
    - tags


release:
  stage: release
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker pull nib0r/docker-flow-proxy-letsencrypt:${CI_BUILD_REF_NAME}
    - docker tag nib0r/docker-flow-proxy-letsencrypt:${CI_BUILD_REF_NAME} nib0r/docker-flow-proxy-letsencrypt:latest
    - docker push nib0r/docker-flow-proxy-letsencrypt:latest
  tags:
    - ks2.nibor.me
  only:
    - master


release_tags:
  stage: release
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build -t nib0r/docker-flow-proxy-letsencrypt:${CI_BUILD_TAG} .
    - docker push nib0r/docker-flow-proxy-letsencrypt:$CI_BUILD_TAG
  only:
    - tags

