sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version # for verification

script:
- pip install -r requirements-test.txt
- pytest tests.py