version: "3"
services:
  whoami:
    image: jwilder/whoami
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=https://git.nibor.me
        - com.df.letsencrypt.host=git.nibor.me
        - com.df.letsencrypt.email=robinlucbernet@gmail.com
        - com.df.servicePath=/
        - com.df.port=8000
networks:
  proxy:
    external: true
