site_name: docker-flow-proxy-letsencrypt
pages:
  - Home: index.md
  - Tutorials:
    - Using volumes: tutorial-volumes.md
    - Using DNS challenge: tutorial-challenge-dns.md
  - Configuration: config.md
  - Examples:
    - Using volumes: example-volumes.md
    - Using secrets: example-secrets.md

repo_url: https://github.com/n1b0r/docker-flow-proxy-letsencrypt
site_author: Robin Lucbernet
copyright: Copyright © 2017 Robin Lucbernet
strict: true
theme: 
  name: 'material'
extra:
  palette:
    primary: 'blue'
    accent: 'light blue'
markdown_extensions:
  - toc
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde